"use client";

import { useCallback, useEffect, useState } from "react";
import { X, Copy, Check, FileText } from "lucide-react";

interface CoverLetterModalProps {
  matchId: string;
  onClose: () => void;
}

interface CoverLetter {
  id: string;
  content: string;
  createdAt: string;
}

export default function CoverLetterModal({
  matchId,
  onClose,
}: CoverLetterModalProps) {
  const [coverLetter, setCoverLetter] = useState<CoverLetter | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const fetchCoverLetter = useCallback((signal?: AbortSignal) => {
    queueMicrotask(() => {
      void (async () => {
        if (signal?.aborted) return;

        setIsLoading(true);
        setError(null);

        try {
          const response = await fetch("/api/cover-letter", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ matchId }),
            signal,
          });

          const data = await response.json();

          if (!response.ok) {
            throw new Error(data.error || "Failed to generate cover letter");
          }

          if (!signal?.aborted) {
            setCoverLetter(data.coverLetter);
          }
        } catch (err) {
          if (signal?.aborted) return;
          setError(err instanceof Error ? err.message : "Something went wrong");
        } finally {
          if (!signal?.aborted) {
            setIsLoading(false);
          }
        }
      })();
    });
  }, [matchId]);

  useEffect(() => {
    const controller = new AbortController();
    fetchCoverLetter(controller.signal);

    return () => controller.abort();
  }, [fetchCoverLetter]);

  const handleCopy = async () => {
    if (!coverLetter) return;
    try {
      await navigator.clipboard.writeText(coverLetter.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-hidden flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-stone-200">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-orange-600" />
            <h2 className="text-lg font-bold text-stone-900">
              Your Cover Letter
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 hover:bg-stone-100 rounded-lg transition"
            aria-label="Close"
          >
            <X className="w-5 h-5 text-stone-600" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-6">
          {isLoading && (
            <div className="text-center py-12">
              <div className="inline-flex w-16 h-16 bg-gradient-to-br from-orange-500 to-orange-600 rounded-2xl items-center justify-center mb-4 shadow-lg">
                <FileText className="w-8 h-8 text-white animate-pulse" />
              </div>
              <p className="text-stone-900 font-bold text-lg mb-1">
                Writing your cover letter...
              </p>
              <p className="text-sm text-stone-500">
                Claude is crafting a personalized message
              </p>
            </div>
          )}

          {error && (
            <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-red-700">
              <p className="font-semibold mb-2">
                Couldn&apos;t generate letter
              </p>
              <p className="text-sm mb-3">{error}</p>
              <button
                onClick={() => fetchCoverLetter()}
                className="px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white text-sm font-semibold rounded-lg transition"
              >
                Try again
              </button>
            </div>
          )}

          {coverLetter && (
            <div className="prose prose-stone max-w-none">
              <div className="whitespace-pre-wrap text-stone-800 leading-relaxed text-[15px]">
                {coverLetter.content}
              </div>
            </div>
          )}
        </div>

        {coverLetter && (
          <div className="px-6 py-4 border-t border-stone-200 bg-stone-50 flex items-center justify-between gap-3">
            <p className="text-xs text-stone-500">
              Generated by Claude · Edit before sending
            </p>
            <button
              onClick={handleCopy}
              className={`flex items-center gap-2 px-4 py-2 font-semibold rounded-lg transition ${
                copied
                  ? "bg-emerald-600 text-white"
                  : "bg-stone-900 hover:bg-stone-800 text-white"
              }`}
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy to clipboard
                </>
              )}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
